module GazeboState
{

    struct Vector3
    {
        double x;
        double y;
        double z;
    };

    struct ObjectState
    {
        string<255> target; //@key
		boolean is_static;
        Vector3 pos;
        Vector3 lin_vel;
        Vector3 bounding_box;
    };

    struct DistanceObjectState
    {
        string<255> target; //@key
		string<255> relativeto;
        double distance;
    };
    
    struct MinLaserDistance
    {
    	double min_measured_distance;
    };
	
	struct EnvironmentState
	{
		string<255> world_name; //@key
		sequence<ObjectState,255> objects;
	};
};
